FROM jenkins/base

# RUN wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add - \
#     echo "deb https://pkg.jenkins.io/debian-stable binary\n" >> /etc/apt/sources.list \
#     apt-get -qqy update \
#     && apt-get -qqy --no-install-recommends install \
#     jenkins

RUN wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
RUN echo "deb https://pkg.jenkins.io/debian-stable binary\n" >> /etc/apt/sources.list 
RUN apt-get -qqy update && apt-get -qqy --no-install-recommends install jenkins

EXPOSE 8080
