FROM jenkins/base

RUN wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
RUN sudo sh -c 'echo deb https://pkg.jenkins.io/debian binary/ > /etc/apt/sources.list.d/jenkins.list'
RUN apt-get -qqy update
# RUN sudo apt-get -y install software-properties-common  && \
#     rm -rf /var/lib/apt/lists/*
# RUN sudo add-apt-repository universe
RUN sudo apt-get -y install jenkins

USER jenkins

EXPOSE 8080
